// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDorj-iKed1K-GVYoENEIfdrAc3cNRDcbg',
    appId: '1:691004386199:web:81ce6a7e1d0ac2004172d2',
    messagingSenderId: '691004386199',
    projectId: 'meetworth-cc6a1',
    authDomain: 'meetworth-cc6a1.firebaseapp.com',
    databaseURL: 'https://meetworth-cc6a1-default-rtdb.firebaseio.com',
    storageBucket: 'meetworth-cc6a1.appspot.com',
    measurementId: 'G-60LPC7B3XZ',
    // apiKey: "AIzaSyDorj-iKed1K-GVYoENEIfdrAc3cNRDcbg",
    // appId: "1:691004386199:web:81ce6a7e1d0ac2004172d2",
    // messagingSenderId: "691004386199",
    // projectId: "meetworth-cc6a1",
    // authDomain: "meetworth-cc6a1.firebaseapp.com",
    // databaseURL: "https://meetworth-cc6a1-default-rtdb.firebaseio.com",
    // storageBucket: "meetworth-cc6a1.appspot.com",
    // measurementId: "G-NL4P8E7LZC"
  );
}
